-- ============================================================================
-- Ingesocc SAS — Esquema de base de datos (Supabase / Postgres)
--
-- ⚠️ ESTE ARCHIVO YA NO ES LA FUENTE DE VERDAD.  ⚠️
--
-- El esquema se gestiona ahora con migraciones versionadas:
--
--   supabase/migrations/
--   ├── 20260917000000_initial_schema.sql   (tablas, funciones, triggers)
--   ├── 20260917000001_rls_policies.sql     (Row Level Security)
--   └── 20260917000002_storage_buckets.sql  (buckets + políticas de storage)
--
-- Aplicar con el CLI de Supabase:
--
--   supabase link --project-ref <ref>     # una vez
--   supabase db push                      # aplica migraciones pendientes
--   supabase db reset                     # local: aplica todo + seed.sql
--
-- La semilla de datos (categorías, servicios, content_blocks y proyectos de
-- ejemplo en draft) sigue en supabase/seed.sql; en desarrollo local el CLI la
-- aplica automáticamente tras las migraciones. Este stub queda solo por
-- compatibilidad con referencias antiguas — puede eliminarse cuando nadie lo
-- cite ya.
--
-- Historial: el contenido original de este archivo se migró a las tres
-- migraciones de arriba sin cambios de comportamiento.
-- ============================================================================
